### ISSUE TITLE
Installation instructions seem not to work

### ISSUE THREAD

**Issue by matou** [ioexception-de/website-changes-notifications#1]
The given command
`$ git clone https://github.com/ioexception.de/piratenpad-notifications.git`
I don't know why, though. It says:
`Cloning into 'piratenpad-notifications'...
fatal: https://github.com/ioexception.de/piratenpad-notifications.git/info/refs not found: did you run git update-server-info on the server?`

But the following does work:
`$ git clone git@github.com:ioexception-de/piratenpad-notifications.git`

**Comment by cmichi** [comment]
Ah that damn typo! It has to be `ioexception-de` instead of `ioexception.de`.

So the correct way to clone is
`$ git clone https://github.com/ioexception-de/piratenpad-notifications.git`
